#!/usr/bin/env python3
"""Writes the app-text translation tables for both apps from ui_strings.json:

    mobile/lib/ui_strings.dart   (kUiStrings, read by mobile/lib/i18n.dart)
    web/src/lib/uiStrings.ts     (UI_STRINGS, read by web/src/lib/i18n.ts)

ui_strings.json maps each English UI string, exactly as written in the code,
to its hi/ta/te/mr translation; `{name}` placeholders must appear in every
translation. Run after editing it:  python3 i18n/gen_ui_strings.py

TODO: native_qa — the translations are author-written and have not been
reviewed by native speakers yet.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANGS = ['hi', 'ta', 'te', 'mr']
HEADER = 'GENERATED by i18n/gen_ui_strings.py from i18n/ui_strings.json — do not edit.'


def main():
    table = json.loads((ROOT / 'i18n' / 'ui_strings.json').read_text(encoding='utf-8'))
    for en, tr in table.items():
        want = set(re.findall(r'\{\w+\}', en))
        for lang in LANGS:
            if set(re.findall(r'\{\w+\}', tr[lang])) != want:
                raise SystemExit(f'{lang}: placeholders differ for {en!r}')

    def dart(s):
        return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"

    lines = [f'// {HEADER}', 'const Map<String, Map<String, String>> kUiStrings = {']
    for lang in LANGS:
        lines.append(f"  '{lang}': {{")
        lines += [f'    {dart(en)}: {dart(tr[lang])},' for en, tr in table.items()]
        lines.append('  },')
    lines.append('};')
    (ROOT / 'mobile' / 'lib' / 'ui_strings.dart').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    lines = [f'// {HEADER}', 'export const UI_STRINGS: Partial<Record<string, Record<string, string>>> = {']
    for lang in LANGS:
        lines.append(f'  {lang}: {{')
        lines += [f'    {json.dumps(en, ensure_ascii=False)}: {json.dumps(tr[lang], ensure_ascii=False)},' for en, tr in table.items()]
        lines.append('  },')
    lines.append('};')
    (ROOT / 'web' / 'src' / 'lib' / 'uiStrings.ts').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(table)} strings x {len(LANGS)} languages')


if __name__ == '__main__':
    main()
