#!/usr/bin/env python3
"""Writes the app-text translation tables for both apps from ui_strings.json:

    mobile/lib/ui_strings.dart   (kUiStrings, read by mobile/lib/i18n.dart)
    web/src/lib/uiStrings.ts     (UI_STRINGS, read by web/src/lib/i18n.ts)

ui_strings.json maps each English UI string, exactly as written in the code,
to its hi/ta/te/mr translation; `{name}` placeholders must appear in every
translation. Run after editing it:  python3 ui-strings/gen_ui_strings.py

TODO: native_qa — the translations are author-written and have not been
reviewed by native speakers yet.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANGS = ['hi', 'ta', 'te', 'mr']
HEADER = 'GENERATED by ui-strings/gen_ui_strings.py from ui-strings/ui_strings.json — do not edit.'


def write(path, lines):
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main():
    table = json.loads((ROOT / 'ui-strings' / 'ui_strings.json').read_text(encoding='utf-8'))
    for en, tr in table.items():
        want = set(re.findall(r'\{\w+\}', en))
        for lang in LANGS:
            if set(re.findall(r'\{\w+\}', tr[lang])) != want:
                raise SystemExit(f'{lang}: placeholders differ for {en!r}')

    def dart(s):
        for raw, esc in (('\\', '\\\\'), ("'", "\\'"), ('$', '\\$'), ('\n', '\\n')):
            s = s.replace(raw, esc)
        return f"'{s}'"

    lines = [f'// {HEADER}', 'const Map<String, Map<String, String>> kUiStrings = {']
    for lang in LANGS:
        lines.append(f"  '{lang}': {{")
        lines += [f'    {dart(en)}: {dart(tr[lang])},' for en, tr in table.items()]
        lines.append('  },')
    lines.append('};')
    write(ROOT / 'mobile' / 'lib' / 'ui_strings.dart', lines)

    def ts(s):
        return json.dumps(s, ensure_ascii=False)

    ts_type = 'Partial<Record<string, Record<string, string>>>'
    lines = [f'// {HEADER}', f'export const UI_STRINGS: {ts_type} = {{']
    for lang in LANGS:
        lines.append(f'  {lang}: {{')
        lines += [f'    {ts(en)}: {ts(tr[lang])},' for en, tr in table.items()]
        lines.append('  },')
    lines.append('};')
    write(ROOT / 'web' / 'src' / 'lib' / 'uiStrings.ts', lines)
    print(f'{len(table)} strings x {len(LANGS)} languages')


if __name__ == '__main__':
    main()
