// Colors/spacing/type scale copied verbatim from the tailwind.config the
// Stitch project ("WeatherGPT AI Weather Assistant") embeds in every
// exported screen, so screens pulled from Stitch later drop in without a
// token mismatch. It's a Material Design 3-style palette.

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#afc6ff',
        'inverse-primary': '#afc6ff',
        'on-tertiary-fixed-variant': '#614000',
        'surface-container-low': '#f1f3ff',
        'inverse-surface': '#1d3052',
        'surface-bright': '#f9f9ff',
        'on-background': '#041b3c',
        'on-tertiary-container': '#fffbff',
        'on-primary-fixed': '#001943',
        'on-secondary-fixed-variant': '#004f4f',
        'tertiary-container': '#9d6a00',
        'on-primary-fixed-variant': '#004299',
        'on-secondary-container': '#007070',
        surface: '#f9f9ff',
        'tertiary-fixed': '#ffddb0',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'primary-fixed': '#d9e2ff',
        'on-secondary-fixed': '#002020',
        'on-error': '#ffffff',
        tertiary: '#7d5400',
        'surface-container-highest': '#d7e2ff',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        primary: '#0057c2',
        'surface-container-high': '#e0e8ff',
        'on-tertiary-fixed': '#281800',
        'on-secondary': '#ffffff',
        'surface-tint': '#0059c7',
        'primary-container': '#006ef3',
        'outline-variant': '#c1c6d7',
        secondary: '#006a6a',
        'on-primary': '#ffffff',
        'secondary-fixed': '#7af5f5',
        'tertiary-fixed-dim': '#ffba46',
        'error-container': '#ffdad6',
        'surface-container': '#e8edff',
        outline: '#727786',
        background: '#f9f9ff',
        'inverse-on-surface': '#edf0ff',
        'secondary-fixed-dim': '#5bd9d8',
        'surface-dim': '#cadaff',
        'secondary-container': '#7af5f5',
        'on-surface': '#041b3c',
        'on-surface-variant': '#414755',
        'surface-variant': '#d7e2ff',
        'on-primary-container': '#fefcff',
        // IMD warning colour-code bands (plan.md §2.4) — kept literal,
        // never re-derived from the palette above.
        'imd-green': '#1e7f3c',
        'imd-yellow': '#c99a00',
        'imd-orange': '#d96a0b',
        'imd-red': '#b3261e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        margin: '2rem',
        'space-lg': '1.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'metric-display': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'citation-mono': ['JetBrains Mono'],
        'headline-xl': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'metric-display': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'citation-mono': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
