// Colors/spacing/type scale copied verbatim from the tailwind.config the
// Stitch project ("WeatherGPT AI Weather Assistant") embeds in every
// exported screen, so screens pulled from Stitch later drop in without a
// token mismatch. It's a Material Design 3-style palette.

// Persona themes: every colour that changes with the selected persona or
// Light / Dark appearance is a CSS custom property ("r g b") that
// src/theme/personaTheme.ts's applyTheme() writes on <html>, so the names
// below keep working in every page while their values follow the persona.
// The rest (secondary / tertiary families, IMD bands) stay literal.
const v = (name) => `rgb(var(--c-${name}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': v('primary-fixed-dim'),
        'inverse-primary': v('inverse-primary'),
        'on-tertiary-fixed-variant': '#614000',
        'surface-container-low': v('surface-container-low'),
        'inverse-surface': v('inverse-surface'),
        'surface-bright': v('surface-bright'),
        'on-background': v('on-background'),
        'on-tertiary-container': '#fffbff',
        'on-primary-fixed': v('on-primary-fixed'),
        'on-secondary-fixed-variant': '#004f4f',
        'tertiary-container': '#9d6a00',
        'on-primary-fixed-variant': v('on-primary-fixed-variant'),
        'on-secondary-container': '#007070',
        surface: v('surface'),
        'tertiary-fixed': '#ffddb0',
        'on-tertiary': '#ffffff',
        error: v('error'),
        'primary-fixed': v('primary-fixed'),
        'on-secondary-fixed': '#002020',
        'on-error': v('on-error'),
        tertiary: '#7d5400',
        'surface-container-highest': v('surface-container-highest'),
        'surface-container-lowest': v('surface-container-lowest'),
        'on-error-container': v('on-error-container'),
        primary: v('primary'),
        'surface-container-high': v('surface-container-high'),
        'on-tertiary-fixed': '#281800',
        'on-secondary': '#ffffff',
        'surface-tint': v('surface-tint'),
        'primary-container': v('primary-container'),
        'outline-variant': v('outline-variant'),
        secondary: '#006a6a',
        'on-primary': v('on-primary'),
        'secondary-fixed': '#7af5f5',
        'tertiary-fixed-dim': '#ffba46',
        'error-container': v('error-container'),
        'surface-container': v('surface-container'),
        outline: v('outline'),
        background: v('background'),
        'inverse-on-surface': v('inverse-on-surface'),
        'secondary-fixed-dim': '#5bd9d8',
        'surface-dim': v('surface-dim'),
        'secondary-container': '#7af5f5',
        'on-surface': v('on-surface'),
        'on-surface-variant': v('on-surface-variant'),
        'surface-variant': v('surface-variant'),
        'on-primary-container': v('on-primary-container'),
        // IMD warning colour-code bands (plan.md §2.4) — kept literal,
        // never re-derived from the palette above.
        'imd-green': '#1e7f3c',
        'imd-yellow': '#c99a00',
        'imd-orange': '#d96a0b',
        'imd-red': '#b3261e',
        // Persona tokens beyond the Material slots (mobile PersonaTheme).
        'accent-2': v('accent-2'),
        'accent-2-soft': v('accent-2-soft'),
        'accent-end': v('accent-end'),
        'sky-top': v('sky-top'),
        'sky-bottom': v('sky-bottom'),
        sheet: v('sheet'),
        'cloud-puff': v('cloud-puff'),
        card: v('card'),
        'card-border': v('card-border'),
        tint: v('tint'),
        'tint-strong': v('tint-strong'),
        shadow: v('shadow'),
        ink: v('ink'),
        'ink-muted': v('ink-muted'),
        'nav-bar': v('nav-bar'),
        'nav-idle': v('nav-idle'),
      },
      boxShadow: {
        // The persona-tinted card lift (mobile PersonaTheme.cardShadow).
        card: '0 3px 12px rgb(var(--c-shadow) / var(--shadow-a))',
        chrome: '0 1px 8px rgb(0 0 0 / 0.04)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        card: '1rem',
        sheet: '1.75rem',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        margin: '2rem',
        'space-lg': '1.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'metric-display': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'citation-mono': ['JetBrains Mono'],
        'headline-xl': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'metric-display': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'citation-mono': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
